# Site settings
title: Sheng Xu
email: sheng.xu2@ucalgary.ca
description: > # this means to ignore newlines until "baseurl:"
  Computer Vision, mobile laser scanning, LiDAR
#baseurl: "/Read-Only-Jekyll-Theme" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
