# Site settings
title: Sheng Xu
email: xusheng [AT] njfu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
#baseurl: "/Read-Only-Jekyll-Theme" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
